[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/AlvaroRosado"
[social.params]
icon = "github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/alvaro-rosado/"
[social.params]
icon = "linkedin"

[[social]]
identifier = "rss"
name = "RSS Feed"
url = "/index.xml"
[social.params]
icon = "rss"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:alvaro.rosado93@gmail.com"
[social.params]
icon = "email"